version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
      
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2181:2181'